<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRqNF1GE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRqNF1GE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRqNF1GE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRqNF1GE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRqNF1GE\App_KernelDevDebugContainer([
    'container.build_hash' => 'RqNF1GE',
    'container.build_id' => 'e6c32a4f',
    'container.build_time' => 1705493742,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRqNF1GE');
